export const FILM_LIST_FETCH = 'FILM_LIST_FETCH';
export const FILM_LIST_DATA = 'FILM_LIST_DATA';
export const FILM_LIST_ERROR = 'FILM_LIST_ERROR';

export const ADD_FILM_FETCH = 'ADD_FILM_FETCH';
export const ADD_FILM_DATA = 'ADD_FILM_DATA';
export const ADD_FILM_ERROR = 'ADD_FILM_ERROR';

export const DELETE_FILM_FETCH = 'DELETE_FILM_FETCH';
export const DELETE_FILM_DATA = 'DELETE_FILM_DATA';
export const DELETE_FILM_ERROR = 'DELETE_FILM_ERROR';

export const SEARCH_FILM_FETCH = 'SEARCH_FILM_FETCH';
export const SEARCH_FILM_DATA = 'SEARCH_FILM_DATA';
export const SEARCH_FILM_ERROR = 'SEARCH_FILM_ERROR';

export const UPLOAD_FILM_LIST_FETCH = 'UPLOAD_FILM_LIST_FETCH';
export const UPLOAD_FILM_LIST_DATA = 'UPLOAD_FILM_LIST_DATA';
export const UPLOAD_FILM_LIST_ERROR = 'UPLOAD_FILM_LIST_ERROR';
